const a = {
    userId: '3182065',
    partyno: '216691569056763132',
    sex: '1',
    userName: '王志文',
    mobileNo: '18313494110',
    surname: '王',
    givenName: '志文',
    enName: 'Wang ZhiWen',
    lastName: 'Wang',
    firstName: 'ZhiWen',
    birthDate: '1992-12-12',
    idType: '0',
    idNo: '45092218248158466',
    idAddress: '深圳购福华三路平安金融中心-修改(大陆黑名单)',
    idExpireDate: '2032-12-12',
    taxInfoResp: [
        {
            taxNationalArea: 'CHN',
            taxpayerNo: '123456789',
        },
    ],
    nationalityCode: 'CN',
    nationality: '中国',
    countryAreaCode: 'CHN',
    countryArea: '中国',
    liveAddress: 'Cogycgkcgkckgchcgkccgkclcykclcyl',
    liveCountry: 'BLR',
    liveProvince: 'BLR',
    liveCity: 'HR',
    liveCountryDesc: '白俄罗斯',
    liveProvinceDesc: '白俄罗斯',
    liveCityDesc: '格罗德诺',
    careerType: '01',
    careerTypeDesc: '制造业',
    workCompany: '北京大公司',
    positionCode: '2401',
    workPosition: '制造业管理人员',
    netIncome: '1230000',
    openAccountReasonType: '1',
    isIdcardAddress: '0',
    usedNameResp: []
}